---
title: "Problem Set 0"
author: "Yuna Wu"
date: "2023-09-16"
output: 
    html_document:
        theme: journal
    pdf_document:
        latex_engine: xelatex
knit: (function(inputFile, encoding) {
 rmarkdown::render(inputFile, encoding = encoding, 
 output_format = 'all') 
 })
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## 1. Introduction
### 1.1 My interests in economics and data science
I am very interested in microeconomics and the practical applications of economics.

### 1.2 What made you want to take this class?
I am taking this class because I want to learn how to analyze and utilize numerical and unstructured data to make arguments and draw conclusions. This class
also provides an excellent opportunity to practice econometrics and statistics.
Additionally, I want to challenge myself by exploring the world of data science.

### 1.3 Do you have any ideas for what you would want to do for your project in this class?
not quite sure, I need some recommendations and reference. I am thinking
about something related to Market Basket Analysis.

### 1.4 What are your goals for this class, and what is your plan for after graduation?
By the end of this class, I aim to become proficient in the R programming language and be capable of independently conducting data analysis and drawing conclusions. I am particularly interested in pursuing a career in the consulting field.

## 2. Equation
$$
a^2 + b^2 = c^2
$$